baseurl: /~swaka
# url: https://www.ms.u-tokyo.ac.jp/~swaka
host: 0.0.0.0
livereload: true
timezone: Asia/Tokyo
plugins:
  - jekyll-toc
  - jekyll-typescript-converter
refer:
  key: ref
  default_to_page:
    - lang
num_styles: 10
# dynamic-css.html では 10 とかにすると重いので
_num_styles: 10
collections:
  tests:
    output: true
defaults:
  - scope:
      path: ""
      type: tests
    values:
      backref: list-of-tests
      layout: mylayout
sass:
  style: compressed
  # sourcemap: never
  # ↑scss 内のコメントに Jekyll タグが含まれていると，
  # sourcemap (.css.map) ではそれが処理されてしまう
typescript:
  build_dir: .tsbuild
  default_source_dir: _ts
