baseurl: /~swaka
# url: https://www.ms.u-tokyo.ac.jp/~swaka
host: 0.0.0.0
livereload: true
timezone: Asia/Tokyo
plugins:
  - jekyll-toc
refer:
  key: ref
  default_to_page:
    - lang
num_styles: 2
collections:
  tests:
    output: true
defaults:
  - scope:
      path: "*.md"
    values:
      layout: mylayout
  - scope:
      path: "others/*.md"
    values:
      layout: mylayout
  - scope:
      path: ""
      type: tests
    values:
      backref: list-of-tests
      layout: mylayout
