baseurl: ""
# url: https://www.ms.u-tokyo.ac.jp/~swaka
host: 0.0.0.0
livereload: true
exclude:
  - _plugins  # _plugins/ 変更時に livereload を発動させない (そもそもプラグインは再読み込みされない)
timezone: Asia/Tokyo
plugins:
  - jekyll-toc
  - jekyll-typescript
  - jekyll-math
  - kramdown-math-zotica
  - jekyll-refer
kramdown:
  math_engine: zotica
crossref:
  theorem: 定理
  definition: 定義
  proposition: 命題
  lemma: 補題
  corollary: 系
  remark: 注意
  example: 例
refer:
  key: ref
  default_to_page:
    - lang
num_styles: 10
# dynamic-css.html では 10 とかにすると重いので
_num_styles: 10
collections:
  tests:
    output: true
defaults:
  - scope:
      path: ""
      type: tests
    values:
      backref: list-of-tests
      backref_lang: ja
      layout: mylayout
sass:
  style: compressed
  # sourcemap: never
  # ↑scss 内のコメントに Jekyll タグが含まれていると，
  # sourcemap (.css.map) ではそれが処理されてしまう
typescript:
  build_dir: .tsbuild
  source_dir: _ts
  pages:
    - source_dir: _ts
      source_file: research_ja.ts
      layout: research_layout.html
      destination: research-ja.html
      site_json_file: site.json
      cache: true
      depend:
        - _data/articles.yml
        - _data/talks.yml
      data:
        title: "研究"
        lang: ja
    - source_dir: _ts
      source_file: research_en.ts
      layout: research_layout.html
      destination: research-en.html
      site_json_file: site.json
      cache: true
      depend:
        - _data/articles.yml
        - _data/talks.yml
      data:
        title: "Research"
        lang: en
