source 'https://rubygems.org'

jekyll_version = '3.8.6'
jekyll_version = '4.0.0'

gem 'jekyll', jekyll_version
gem 'nokogiri'
gem 'jekyll-toc'

# group :jekyll_plugins do
#   gem 'jekyll-last-modified-at'
#   gem 'hawkins'
# end
