source 'https://rubygems.org'

jekyll_version = '3.8.6'
jekyll_version = '4.0.0'

gem 'jekyll', jekyll_version
gem 'nokogiri'
gem 'jekyll-toc'
gem 'jekyll-typescript', git: 'git@github.com:shwaka/jekyll-typescript.git'
gem 'rake'

# group :jekyll_plugins do
#   gem 'jekyll-last-modified-at'
#   gem 'hawkins'
# end
