name: Build docusaurus

on:
  push:
    branches: [ master ]
    paths: [ 'docusaurus/**', '.github/workflows/docusaurus.yml' ]
  pull_request:
    branches: [ master ]
    paths: [ 'docusaurus/**', '.github/workflows/docusaurus.yml' ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v2
      - name: Checkout submodule
        run: |
          git submodule init
          git submodule update
      - uses: actions/setup-node@v2
        with:
          node-version: 14.x
          cache: 'npm'
          cache-dependency-path: docusaurus/package-lock.json
      - run: npm ci
        working-directory: docusaurus
      - name: Build site
        run: npm run build
        working-directory: docusaurus
      - name: Deploy to shwaka/shwaka.github.io
        uses: peaceiris/actions-gh-pages@v3
        with:
          # external_repository は secrets.GITHUB_TOKEN じゃ駄目
          personal_token: ${{ secrets.PERSONAL_TOKEN }}
          external_repository: shwaka/shwaka.github.io
          publish_dir: docusaurus/build
          publish_branch: master
